
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 26;
  public static final int REGISTRO = 19;
  public static final int TIPO = 7;
  public static final int CCIERRE = 15;
  public static final int PCIERRE = 13;
  public static final int ENTERO = 34;
  public static final int RESTA = 43;
  public static final int DOS_PUNTOS = 9;
  public static final int CAPERTURA = 14;
  public static final int ARRAY = 11;
  public static final int DELETE = 31;
  public static final int WRITE = 28;
  public static final int NOT = 46;
  public static final int AND = 40;
  public static final int OR = 41;
  public static final int DIV = 45;
  public static final int BEGIN = 3;
  public static final int SUMA = 39;
  public static final int IF = 21;
  public static final int PUNTO_COMA = 5;
  public static final int ID = 33;
  public static final int OP_RELACIONAL = 38;
  public static final int OF = 16;
  public static final int EOF = 0;
  public static final int ASIG = 20;
  public static final int TIPO_BASICO = 17;
  public static final int NEW = 30;
  public static final int error = 1;
  public static final int MUL = 44;
  public static final int NULO = 32;
  public static final int COMA = 10;
  public static final int CADENA = 36;
  public static final int MOD = 42;
  public static final int PUNTERO = 18;
  public static final int REAL = 35;
  public static final int ELSE = 23;
  public static final int PUNTO = 2;
  public static final int PAPERTURA = 12;
  public static final int NL = 29;
  public static final int READ = 27;
  public static final int WHILE = 24;
  public static final int THEN = 22;
  public static final int END = 4;
  public static final int BOOLEANO = 37;
  public static final int PROC = 8;
  public static final int VAR = 6;
  public static final int DO = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUNTO",
  "BEGIN",
  "END",
  "PUNTO_COMA",
  "VAR",
  "TIPO",
  "PROC",
  "DOS_PUNTOS",
  "COMA",
  "ARRAY",
  "PAPERTURA",
  "PCIERRE",
  "CAPERTURA",
  "CCIERRE",
  "OF",
  "TIPO_BASICO",
  "PUNTERO",
  "REGISTRO",
  "ASIG",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "SEQ",
  "READ",
  "WRITE",
  "NL",
  "NEW",
  "DELETE",
  "NULO",
  "ID",
  "ENTERO",
  "REAL",
  "CADENA",
  "BOOLEANO",
  "OP_RELACIONAL",
  "SUMA",
  "AND",
  "OR",
  "MOD",
  "RESTA",
  "MUL",
  "DIV",
  "NOT"
  };
}

